"""
StudyMate AI — Quiz Generator Tool.

Generates multiple-choice quiz questions on any topic
with varying difficulty levels and explanations.
"""

import json
import random


def register_tools(mcp) -> None:
    """Register quiz generator tools with the MCP server."""

    @mcp.tool()
    def quiz_generator(
        topic: str,
        difficulty: str = "medium",
        num_questions: int = 5,
    ) -> str:
        """
        Generate multiple-choice quiz questions on a topic.

        Creates educational quiz questions with 4 options each,
        correct answers, and explanations for learning.

        Args:
            topic: The topic to generate questions about.
            difficulty: Quiz difficulty (easy/medium/hard).
            num_questions: Number of questions to generate (1-20).

        Returns:
            JSON string with quiz questions, options, and answers.
        """
        num_questions = max(1, min(num_questions, 20))

        # Template-based question generation
        # In production, these would be generated by the LLM,
        # but the tool provides structure and validation.
        questions = []

        question_templates = _get_question_templates(topic, difficulty)

        for i in range(num_questions):
            template_idx = i % len(question_templates)
            template = question_templates[template_idx]

            question = {
                "question_number": i + 1,
                "question": template["question"].format(topic=topic),
                "options": template["options"],
                "correct_answer": template["correct_answer"],
                "explanation": template["explanation"].format(topic=topic),
                "difficulty": difficulty,
            }
            questions.append(question)

        result = {
            "success": True,
            "topic": topic,
            "difficulty": difficulty,
            "total_questions": len(questions),
            "questions": questions,
            "instructions": (
                "Read each question carefully. Select the best answer from "
                "the given options. Review the explanations after completing the quiz."
            ),
        }

        return json.dumps(result, indent=2)


def _get_question_templates(topic: str, difficulty: str) -> list[dict]:
    """
    Get question templates based on topic and difficulty.

    These serve as structural templates. In practice, the AI agent
    uses the LLM to generate topic-specific content, while this tool
    provides the framework and validation.
    """
    easy_templates = [
        {
            "question": f"What is the fundamental concept of {topic}?",
            "options": [
                f"The basic principles and definitions of {topic}",
                f"An advanced application of {topic}",
                f"A historical overview of {topic}",
                f"A mathematical proof in {topic}",
            ],
            "correct_answer": f"The basic principles and definitions of {topic}",
            "explanation": "Understanding the fundamentals is the first step to mastering {topic}.",
        },
        {
            "question": f"Which of the following best describes {topic}?",
            "options": [
                f"A systematic study of core concepts in {topic}",
                f"An unrelated field of study",
                f"Only applicable in theoretical scenarios",
                f"A deprecated area of knowledge",
            ],
            "correct_answer": f"A systematic study of core concepts in {topic}",
            "explanation": "{topic} involves systematic study and understanding of its core principles.",
        },
        {
            "question": f"Why is it important to study {topic}?",
            "options": [
                f"It builds foundational knowledge needed for advanced concepts",
                "It is not particularly important",
                "It only matters for exams",
                "It has no practical applications",
            ],
            "correct_answer": f"It builds foundational knowledge needed for advanced concepts",
            "explanation": "Studying {topic} provides the foundation for understanding more complex ideas.",
        },
        {
            "question": f"What is the best approach to learning {topic}?",
            "options": [
                "Practice regularly and understand concepts step by step",
                "Memorize everything without understanding",
                "Only study the night before an exam",
                "Skip the basics and jump to advanced topics",
            ],
            "correct_answer": "Practice regularly and understand concepts step by step",
            "explanation": "Regular practice with conceptual understanding is the most effective way to learn {topic}.",
        },
        {
            "question": f"Which study method is most effective for {topic}?",
            "options": [
                "Active recall and spaced repetition",
                "Passive reading only",
                "Watching videos without taking notes",
                "Cramming everything in one session",
            ],
            "correct_answer": "Active recall and spaced repetition",
            "explanation": "Active recall and spaced repetition are proven methods for long-term retention of {topic}.",
        },
    ]

    medium_templates = [
        {
            "question": f"How do the key concepts in {topic} relate to each other?",
            "options": [
                "They form an interconnected framework building on each other",
                "They are completely independent concepts",
                "They contradict each other",
                "They are only relevant in isolation",
            ],
            "correct_answer": "They form an interconnected framework building on each other",
            "explanation": "In {topic}, concepts build upon each other creating a comprehensive understanding.",
        },
        {
            "question": f"What is a common misconception about {topic}?",
            "options": [
                f"That {topic} only involves memorization without understanding",
                f"That {topic} requires systematic study",
                f"That practice is important for {topic}",
                f"That {topic} has real-world applications",
            ],
            "correct_answer": f"That {topic} only involves memorization without understanding",
            "explanation": "{topic} requires deep understanding beyond mere memorization.",
        },
        {
            "question": f"How can you apply {topic} knowledge in practice?",
            "options": [
                "By solving problems and analyzing real-world scenarios",
                "By only reading textbooks",
                "By avoiding practical exercises",
                "By focusing solely on theory",
            ],
            "correct_answer": "By solving problems and analyzing real-world scenarios",
            "explanation": "Practical application through problem-solving reinforces {topic} knowledge effectively.",
        },
        {
            "question": f"What distinguishes an intermediate understanding of {topic} from a beginner level?",
            "options": [
                "Ability to connect concepts and solve complex problems",
                "Just knowing the definitions",
                "Being able to recite facts",
                "Having read more textbooks",
            ],
            "correct_answer": "Ability to connect concepts and solve complex problems",
            "explanation": "Intermediate understanding of {topic} means connecting ideas and applying them creatively.",
        },
        {
            "question": f"Which analytical skill is most crucial when studying {topic}?",
            "options": [
                "Critical thinking and logical reasoning",
                "Speed reading",
                "Memorization capacity",
                "Note-taking speed",
            ],
            "correct_answer": "Critical thinking and logical reasoning",
            "explanation": "Critical thinking enables deeper analysis and understanding of {topic} concepts.",
        },
    ]

    hard_templates = [
        {
            "question": f"How would you evaluate the effectiveness of different approaches to {topic}?",
            "options": [
                "By analyzing outcomes, comparing methodologies, and measuring understanding",
                "By choosing the easiest approach",
                "By following only one textbook",
                "By avoiding critical analysis",
            ],
            "correct_answer": "By analyzing outcomes, comparing methodologies, and measuring understanding",
            "explanation": "Evaluating approaches to {topic} requires systematic analysis and comparison of results.",
        },
        {
            "question": f"What advanced strategy would you recommend for mastering {topic}?",
            "options": [
                "Teach others, solve novel problems, and synthesize across domains",
                "Re-read the same material repeatedly",
                "Focus only on exam-relevant portions",
                "Avoid challenging problems",
            ],
            "correct_answer": "Teach others, solve novel problems, and synthesize across domains",
            "explanation": "Advanced mastery of {topic} comes from teaching, solving novel challenges, and cross-domain synthesis.",
        },
        {
            "question": f"How would you design a comprehensive assessment for {topic}?",
            "options": [
                "Combine theoretical questions, practical problems, and analytical challenges",
                "Only use multiple-choice questions",
                "Focus exclusively on definitions",
                "Use only True/False questions",
            ],
            "correct_answer": "Combine theoretical questions, practical problems, and analytical challenges",
            "explanation": "A thorough assessment of {topic} covers theory, application, and analysis.",
        },
        {
            "question": f"What is the relationship between {topic} and related fields?",
            "options": [
                "They share foundational principles and complement each other",
                "They are completely unrelated",
                "One makes the other obsolete",
                "They contradict each other",
            ],
            "correct_answer": "They share foundational principles and complement each other",
            "explanation": "{topic} connects with related disciplines through shared principles and methodologies.",
        },
        {
            "question": f"How do current developments impact the study of {topic}?",
            "options": [
                "They expand understanding and create new areas of exploration",
                "They make traditional knowledge irrelevant",
                "They have no impact on the field",
                "They simplify everything to trivial problems",
            ],
            "correct_answer": "They expand understanding and create new areas of exploration",
            "explanation": "Modern developments continually expand the scope and depth of {topic}.",
        },
    ]

    templates = {
        "easy": easy_templates,
        "medium": medium_templates,
        "hard": hard_templates,
    }

    return templates.get(difficulty, medium_templates)
